services:
  mongo:
    hostname: mongo
    image: mongo
    expose:
      - 27017
    ports:
      - "27017:27017"
    healthcheck:
      test: [ "CMD","echo","db.adminCommand('ping')", ">","script.js", "mongosh", "<", "script.js" ]
      interval: 10s
      timeout: 5s
      retries: 10
