services:
  - docker:dind
stages:
  - build
  - qa
  - e2e
  - coverage
  - reporting
  - verify
  - test
  - docker-compose
  - update

variables:
  MAVEN_OPTS: "-Dhttps.protocols=TLSv1.2 -Dmaven.repo.local=$CI_PROJECT_DIR/.m2/repository -Dorg.slf4j.simpleLogger.log.org.apache.maven.cli.transfer.Slf4jMavenTransferListener=WARN -Dorg.slf4j.simpleLogger.showDateTime=true -Djava.awt.headless=true"
  MAVEN_CLI_OPTS: "--batch-mode --errors --fail-at-end --show-version -DinstallAtEnd=true -DdeployAtEnd=true"
  CODECOV_TOKEN: $CODECOV_TOKEN
  COVERALLS_REPO_TOKEN: $COVERALLS_REPO_TOKEN
  CODACY_PROJECT_TOKEN: $CODACY_PROJECT_TOKEN
  DOCKER_HOST: "tcp://docker:2375"
  DOCKER_TLS_CERTDIR: ""
  DOCKER_DRIVER: overlay2

image: maven:3-openjdk-17

cache:
  paths:
    - .m2/repository/

.verify: &verify
  stage: test
  script:
    - 'mvn $MAVEN_CLI_OPTS verify'
  except:
    - master
verify:
  <<: *verify

before_script:
  - apt-get update -y
  - apt-get upgrade -y
  - apt-get install build-essential -y
  - bash latest-compose.sh
#  - apt-get install -y docker-compose
#  - apt-get install -y npm
#  - npm install --global yarn
#  - curl -o- https://raw.githubusercontent.com/nvm-sh/nvm/v0.39.1/install.sh | bash
#  - source ~/.bashrc
#  - nvm install --lts

build:
  image: maven:3.8-openjdk-17-slim
  stage: build
  cache:
    - key: MAVEN
      paths:
        - video-series-command/target/
        - video-series-core/target/
        - video-series-query/target/
  script:
    - make no-test

qa:
  image: maven:3.8-openjdk-17-slim
  stage: build
  cache:
    - key: MAVEN
      paths:
        - video-series-command/target/
        - video-series-core/target/
        - video-series-query/target/
  script:
    - mvn test
  needs:
    - build
      
vma-series-electron-e2e:
  image: node:16
  stage: e2e
  script:
    - make dcup-full-action
    - make cypress-electron
  only:
    - master
  needs:
    - qa
  cache:
    - key: MAVEN
      paths:
        - video-series-command/target/
        - video-series-core/target/
        - video-series-query/target/
  allow_failure: true
  timeout: 10m

vma-series-chrome-e2e:
  image: node:16
  stage: e2e
  script:
    - make dcup-full-action
    - make cypress-chrome
  only:
    - master
  needs:
    - qa
  cache:
    - key: MAVEN
      paths:
        - video-series-command/target/
        - video-series-core/target/
        - video-series-query/target/

vma-series-firefox-e2e:
  image: node:16
  stage: e2e
  script:
    - make dcup-full-action
    - make cypress-firefox
  only:
    - master
  needs:
    - qa
  cache:
    - key: MAVEN
      paths:
        - video-series-command/target/
        - video-series-core/target/
        - video-series-query/target/

vma-series-edge-e2e:
  image: node:16
  stage: e2e
  script:
    - make dcup-full-action
    - make cypress-edge
  only:
    - master
  needs:
    - qa
  cache:
    - key: MAVEN
      paths:
        - video-series-command/target/
        - video-series-core/target/
        - video-series-query/target/


coverage:
  image: maven:3.8-openjdk-17-slim
  stage: coverage
  cache:
    - key: MAVEN
      paths:
        - video-series-command/target/
        - video-series-core/target/
        - video-series-query/target/
  script:
    - mvn jacoco:prepare-agent package jacoco:report
  only:
    - master
  needs:
    - build

reporting:
  image: maven:3.8-openjdk-17-slim
  stage: reporting
  cache:
    - key: MAVEN
      paths:
        - video-series-command/target/
        - video-series-core/target/
        - video-series-query/target/
  script:
    - mvn omni-coveragereporter:report
  only:
    - master
  needs:
    - coverage
    - vma-series-edge-e2e
    - vma-series-chrome-e2e
    - vma-series-firefox-e2e
    - vma-series-electron-e2e

update-dependencies:
  image: renovate/renovate
  stage: update
  before_script:
    - ''
  script:
    - export RENOVATE_CONFIG=$(< renovate.json)
    - renovate
  only:
    - master
  needs: []
