services:
  postgres:
    hostname: postgres
    build:
      context: ./docker-psql/.
    environment:
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=admin
      - POSTGRES_MULTIPLE_DATABASES=vsa
    healthcheck:
      test: [ "CMD", "pg_isready", "-U", "postgres" ]
      interval: 10s
      timeout: 5s
      retries: 10

  mongo:
    hostname: mongo
    image: mongo
    healthcheck:
      test: [ "CMD","echo","db.adminCommand('ping')", ">","script.js", "mongosh", "<", "script.js" ]
      interval: 10s
      timeout: 5s
      retries: 10
