services:
  command:
    hostname: command
    build:
      context: ./video-series-command/.
    depends_on:
      postgres-es:
        condition: service_healthy
      postgres:
        condition: service_healthy

  query:
    hostname: query
    build:
      context: ./video-series-query/.
    depends_on:
      postgres-es:
        condition: service_healthy
      postgres:
        condition: service_healthy
