name: VSA Build and reporting

on:
  push:
    branches: [ master ]

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v4
    - name: Set up JDK 19
      uses: actions/setup-java@v4
      with:
        java-version: '19'
        distribution: 'adopt'
        cache: maven

    - name: Build and Test
      run:  mvn clean install jacoco:prepare-agent package jacoco:report

    - name: Coverage Reports
      run: mvn omni-coveragereporter:report
      env:
         COVERALLS_REPO_TOKEN: ${{ secrets.COVERALLS_REPO_TOKEN }}
         CODECOV_TOKEN: ${{ secrets.CODECOV_TOKEN }}
         CODACY_PROJECT_TOKEN: ${{ secrets.CODACY_PROJECT_TOKEN }}

    - name: Version statuses
      run: make version-status
