name: VSA Mono Build

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v4
    - name: Set up JDK 19
      uses: actions/setup-java@v4
      with:
        java-version: '19'
        distribution: 'adopt'
        cache: maven

    - name: Build fast
      run:  mvn clean install -DskipTests

    - name: Build mono
      run: cd video-series-mono && mvn clean install
