name: VSA Pull Request

on:
  push:
    branches:
      - '**'
      - '!master'
  pull_request:
    branches:
      - '**'

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v4
    - name: Set up JDK 19
      uses: actions/setup-java@v4
      with:
        java-version: '19'
        distribution: 'adopt'
        cache: maven

    - name: Build with Maven
      run:  mvn clean install jacoco:prepare-agent package jacoco:report

    - name: Version statuses
      run: make version-status

