name: VSA Mono Build

on:
  pull_request:
    branches: [ master ]

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v3
    - name: Set up JDK 17
      uses: actions/setup-java@v3
      with:
        java-version: '17'
        distribution: 'adopt'
        cache: maven

    - name: Build fast
      run:  mvn clean install -DskipTests

    - name: Build mono
      run: cd video-series-mono && mvn clean install
