name: VSA e2e-video-series-app

on: push

jobs:
  e2e-electron:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v5
      - name: Set up JDK 21
        uses: actions/setup-java@v5
        with:
          java-version: '21'
          distribution: 'adopt'
          cache: maven

      - name: Start Docker
        run: make dcup-full-action

      - name: Run Cypress
        run: make cypress-electron

  e2e-chrome:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v5
      - name: Set up JDK 21
        uses: actions/setup-java@v5
        with:
          java-version: '21'
          distribution: 'adopt'
          cache: maven

      - name: Start Docker
        run: make dcup-full-action

      - name: Run Cypress
        run: make cypress-chrome

  e2e-firefox:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v5
      - name: Set up JDK 21
        uses: actions/setup-java@v5
        with:
          java-version: '21'
          distribution: 'adopt'
          cache: maven

      - name: Start Docker
        run: make dcup-full-action

      - name: Run Cypress
        run: make cypress-firefox

  e2e-edge:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v5
      - name: Set up JDK 21
        uses: actions/setup-java@v5
        with:
          java-version: '21'
          distribution: 'adopt'
          cache: maven

      - name: Start Docker
        run: make dcup-full-action

      - name: Run Cypress
        run: make cypress-edge
